--insert into company (`id`, `country`, `email`, `name`, `phoneNumber`, `uuid`, `website`)values (11, 'country', 'email', 'name', 'phoneNumber', 'uuid', 'website')
--insert into subscriptionOrder (`id`, `editionCode`, `pricingDuration`)values (11, 'editionCode', 'pricing')
--insert into users (`id`, `email`, `firstName`, `language`, `lastName`, `openId`, `uuid`)values (11, 'email', 'firstName','language', 'lastName', 'openId', 'uuid')
--insert into subscription (`company_id`, `subscriptionOrder_id`, `user_id`, `id`)values (11, 11, 11, 11)